# Generated by Django 3.0.1 on 2020-01-22 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amt',
            fields=[
                ('amt', models.CharField(db_column='Amt', max_length=40, primary_key=True, serialize=False)),
                ('hofamt', models.CharField(db_column='Hofamt', max_length=50)),
                ('gnd', models.CharField(db_column='GND', max_length=10)),
                ('rang', models.PositiveIntegerField(db_column='Rang')),
                ('aktiv', models.PositiveIntegerField(db_column='Aktiv')),
            ],
            options={
                'db_table': 'amt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Archiv',
            fields=[
                ('sigle', models.CharField(db_column='Sigle', max_length=50, primary_key=True, serialize=False)),
                ('bestand', models.CharField(db_column='Bestand', max_length=50)),
            ],
            options={
                'db_table': 'archiv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hofstaat',
            fields=[
                ('hofherr', models.CharField(db_column='Hofherr', max_length=4, primary_key=True, serialize=False)),
                ('bezeichnung', models.CharField(db_column='Bezeichnung', max_length=50)),
            ],
            options={
                'db_table': 'hofstaat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Literatur',
            fields=[
                ('literatur', models.SmallAutoField(db_column='Literatur', primary_key=True, serialize=False)),
                ('jahr', models.PositiveSmallIntegerField(db_column='Jahr')),
                ('titelaufnahme', models.TextField(db_column='Titelaufnahme')),
                ('signatur', models.CharField(db_column='Signatur', max_length=100)),
                ('credits', models.CharField(db_column='Credits', max_length=100)),
                ('url', models.CharField(db_column='URL', max_length=200)),
                ('k', models.CharField(db_column='K', max_length=1)),
            ],
            options={
                'db_table': 'literatur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ort',
            fields=[
                ('b', models.DecimalField(blank=True, db_column='B', decimal_places=4, max_digits=7, null=True)),
                ('l', models.DecimalField(blank=True, db_column='L', decimal_places=4, max_digits=7, null=True)),
                ('y', models.CharField(db_column='Y', max_length=2)),
                ('ort', models.CharField(db_column='Ort', max_length=60, primary_key=True, serialize=False)),
                ('la', models.CharField(max_length=60)),
                ('en', models.CharField(max_length=60)),
                ('fr', models.CharField(max_length=60)),
                ('nl', models.CharField(max_length=60)),
                ('es', models.CharField(max_length=60)),
                ('it', models.CharField(max_length=60)),
                ('ro', models.CharField(max_length=60)),
                ('pl', models.CharField(max_length=60)),
                ('cs', models.CharField(max_length=60)),
                ('sk', models.CharField(max_length=60)),
                ('hu', models.CharField(max_length=60)),
                ('si', models.CharField(max_length=60)),
                ('hr', models.CharField(max_length=60)),
                ('xy', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'ort',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('f41', models.SmallAutoField(db_column='F41', primary_key=True, serialize=False)),
                ('zlabel', models.CharField(db_column='ZLabel', max_length=100)),
                ('f13', models.CharField(db_column='F13', max_length=20)),
                ('f14', models.CharField(db_column='F14', max_length=20)),
                ('f16', models.CharField(db_column='F16', max_length=120)),
                ('f24', models.CharField(db_column='F24', max_length=1)),
                ('kommentar', models.TextField(db_column='Kommentar')),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quelle',
            fields=[
                ('quelle', models.CharField(db_column='Quelle', max_length=12, primary_key=True, serialize=False)),
                ('signatur', models.CharField(db_column='Signatur', max_length=48)),
                ('paginierung', models.CharField(db_column='Paginierung', max_length=4)),
                ('kurztitel', models.CharField(db_column='Kurztitel', max_length=60)),
                ('laufzeit', models.CharField(db_column='Laufzeit', max_length=9)),
                ('incipit', models.TextField(db_column='Incipit')),
                ('beschreibung', models.TextField(db_column='Beschreibung')),
                ('kommentar', models.TextField(db_column='Kommentar')),
                ('archivplan', models.CharField(db_column='Archivplan', max_length=100)),
                ('editionen', models.CharField(db_column='Editionen', max_length=120)),
                ('restrict', models.PositiveIntegerField(db_column='Restrict')),
            ],
            options={
                'db_table': 'quelle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('spalte', models.SmallAutoField(db_column='Spalte', primary_key=True, serialize=False)),
                ('stapel', models.CharField(db_column='Stapel', max_length=90)),
                ('dateiname', models.CharField(db_column='Dateiname', max_length=30)),
                ('seite', models.CharField(db_column='Seite', max_length=4)),
                ('x', models.PositiveSmallIntegerField(db_column='X')),
                ('y', models.PositiveSmallIntegerField(db_column='Y')),
                ('inserted_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'scan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('c', models.CharField(db_column='C', max_length=16, primary_key=True, serialize=False)),
                ('amt', models.CharField(db_column='Amt', max_length=60, unique=True)),
                ('beschreibung', models.TextField(db_column='Beschreibung')),
            ],
            options={
                'db_table': 'schema',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transkriptionen',
            fields=[
                ('eintrag', models.AutoField(db_column='Eintrag', primary_key=True, serialize=False)),
                ('seite', models.CharField(db_column='Seite', max_length=4)),
                ('laufnr', models.CharField(db_column='Laufnr', max_length=10)),
                ('name', models.CharField(db_column='Name', max_length=200)),
                ('dienstbeginn', models.CharField(db_column='Dienstbeginn', max_length=20)),
                ('erwaehnung', models.CharField(db_column='Erwaehnung', max_length=20)),
                ('abraitung', models.CharField(db_column='Abraitung', max_length=20)),
                ('promotion', models.CharField(db_column='Promotion', max_length=20)),
                ('erstaufnahme', models.CharField(db_column='Erstaufnahme', max_length=3)),
                ('quellenkommentar', models.TextField(db_column='Quellenkommentar')),
                ('bearbeiterkommentar', models.TextField(db_column='Bearbeiterkommentar')),
                ('anmerkung', models.CharField(db_column='Anmerkung', max_length=200)),
                ('sort', models.CharField(db_column='Sort', max_length=20)),
            ],
            options={
                'db_table': 'transkriptionen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Beziehung',
            fields=[
                ('f41x', models.OneToOneField(db_column='F41X', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='parent_or_husband', serialize=False, to='stats.Person')),
                ('art', models.IntegerField(db_column='Art')),
                ('text', models.CharField(db_column='Text', max_length=20)),
            ],
            options={
                'db_table': 'beziehung',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bild',
            fields=[
                ('f41', models.OneToOneField(db_column='F41', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='stats.Person')),
                ('credits', models.CharField(db_column='Credits', max_length=200)),
                ('link', models.CharField(db_column='Link', max_length=255)),
                ('art', models.CharField(db_column='Art', max_length=1)),
                ('cache', models.PositiveIntegerField(db_column='Cache')),
                ('source', models.CharField(db_column='Source', max_length=255)),
            ],
            options={
                'db_table': 'bild',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Konkordanz',
            fields=[
                ('f41', models.OneToOneField(db_column='F41', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='stats.Person')),
                ('referenz', models.CharField(db_column='Referenz', max_length=6)),
                ('f45', models.CharField(db_column='F45', max_length=90)),
                ('status', models.CharField(db_column='Status', max_length=1)),
            ],
            options={
                'db_table': 'konkordanz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nachweis',
            fields=[
                ('f41', models.OneToOneField(db_column='F41', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='stats.Person')),
                ('seiten', models.CharField(db_column='Seiten', max_length=20)),
                ('kommentar', models.CharField(db_column='Kommentar', max_length=255)),
            ],
            options={
                'db_table': 'nachweis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('eintrag', models.OneToOneField(db_column='Eintrag', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='stats.Transkriptionen')),
                ('x', models.PositiveSmallIntegerField(db_column='X')),
                ('y', models.PositiveSmallIntegerField(db_column='Y')),
            ],
            options={
                'db_table': 'segment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Treffer',
            fields=[
                ('f41', models.OneToOneField(db_column='F41', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='stats.Person')),
                ('katalog', models.CharField(db_column='Katalog', max_length=6)),
                ('treffer', models.PositiveSmallIntegerField(db_column='Treffer')),
                ('url', models.CharField(db_column='URL', max_length=200)),
            ],
            options={
                'db_table': 'treffer',
                'managed': False,
            },
        ),
    ]
